plass:
  elvers_params:
    input_options:
      read:
        - kmer_trimmed
        - trimmed
        - raw
    output_options:
      plass_fasta:
        input: any
        outdir: assembly
        extensions:
          reference_extensions: # use this extension only for all output of this assembler
            - _plass
          base:
            - .fasta
    
    help: "Plass (Protein-Level ASSembler) is a software to assemble short read sequencing data on a protein level. The main purpose of Plass is the assembly of complex metagenomic datasets." 
    citations:
      - "Steinegger M, Mirdita M and Soeding J. Protein-level assembly increases protein sequence recovery from metagenomic samples manyfold. biorxiv, doi: doi.org/10.1101/386110 (2018)"

  program_params:
    inputs:
      - kmer_trimmed
    # do we want to assemble the single reads with pe reads?
    add_single_to_paired: False
    tmpdir: ""
    extra: ''
