language: python
os: linux
dist: xenial

cache:
  timeout: 1000
  directories:
    - $HOME/miniconda

before_install:
- ls -FC $HOME/miniconda
- if test -e $HOME/miniconda/bin; then
    echo "miniconda already installed.";
  else
    echo "Installing miniconda.";
    rm -fr $HOME/miniconda;
    wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    bash miniconda.sh -b -p $HOME/miniconda;
    ls -FC $HOME/miniconda;
  fi

install:
  - export PATH="$HOME/miniconda/bin:$PATH";
  - hash -r
  - chmod -R a-w $HOME/miniconda;
  - chmod +w $HOME/miniconda/env;
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda config --add channels defaults
  - conda config --add channels bioconda
  - conda config --add channels conda-forge
  - rm -fr $HOME/miniconda/envs/test-env
  - conda env create --file environment.yml -n test-env
  - source activate test-env

script:
  - ./run_eelpond nema-download.yaml assemble -t 4
  - rm -fr $HOME/miniconda/envs/test-env $HOME/miniconda/pkgs/cache
  - find $HOME/miniconda -type f -printf '%TY-%Tm-%Td %TT %p\n' | sort -r | head
