language: python
os: linux
dist: xenial

cache:
  timeout: 1000
  directories:
    - $HOME/miniconda

before_install:
- ls -FC $HOME/miniconda
- if test -e $HOME/miniconda/bin; then
    echo "miniconda already installed.";
  else
    echo "Installing miniconda.";
    rm -fr $HOME/miniconda;
    wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    bash miniconda.sh -b -p $HOME/miniconda;
    export PATH="$HOME/miniconda/bin:$PATH";
    conda config --set always_yes yes --set changeps1 no;
    conda config --add channels defaults;
    conda config --add channels bioconda;
    conda config --add channels conda-forge;
  fi

install:
  - export PATH="$HOME/miniconda/bin:$PATH";
  - conda info -a;
  - ls -FC $HOME/miniconda;
  - hash -r;
  - rm -fr $HOME/miniconda/envs/test-env
  - conda env create --file environment.yml -n test-env
  - source activate test-env

script:
  - pytest -v
  - ./run_eelpond examples/nema.yaml get_data -t 4 --restart_times=3
  - ./run_eelpond examples/nema.yaml assemble -t 4
  - ./run_eelpond examples/yeast.yaml quantify diffexp -t 4 --restart_times=3
  - rm -fr $HOME/miniconda/envs/test-env $HOME/miniconda/pkgs/cache
  - find $HOME/miniconda -type f -printf '%TY-%Tm-%Td %TT %p\n' | sort -r | head
