channels:
  - bioconda
  - defaults
  - conda-forge
dependencies:
  - python >=3.6
  - snakemake >=5.8.1
  - yaml
  - pandas
  - graphviz
  - networkx
  - pygments
  - pygraphviz
  - psutil
  - pytest
  - jinja2
