#! /usr/bin/env python
"""
Execution script for snakemake eelpond.
"""
# ref: https://github.com/ctb/2018-snakemake-cli/blob/master/run
import argparse
import os
import sys
import pprint
import yaml
import glob
import collections
import snakemake

def find_Snakefile(workdir):
    snakefile = os.path.join(workdir, 'Snakefile')
    assert os.path.exists(snakefile), 'Error: cannot find Snakefile at {}\n'.format(snakefile)
    return snakefile

def find_yaml(workdir, filename, name): 
    # find the workflow config file
    workflowfile = None
    if os.path.exists(filename) and not os.path.isdir(filename):
        workflowfile = filename
    else:
        for suffix in ('', '.yaml', '.yml'):
            tryfile = os.path.join(workdir, filename + suffix)
            if os.path.exists(tryfile) and not os.path.isdir(tryfile):
                sys.stderr.write('\tFound {} file at {}\n'.format(name, tryfile))
                workflowfile = tryfile
                break
    assert workflowfile, 'Error, cannot find specified {} file {}\n'.format(name, filename)
    return workflowfile

def build_params(workdir):
    rule_params_files = glob.glob(os.path.join(workdir, 'rules','*/*_params.yaml'))
    paramsD = {}
    for f in rule_params_files:
        with open(f, 'r') as stream:
            try:
                paramsD.update(yaml.load(stream))
            except yaml.YAMLError as exc:
                print(exc)
    return paramsD

def read_yaml(filename):
    with open(filename, 'r') as stream:
        try:
            yamlD = yaml.load(stream)
        except yaml.YAMLError as exc:
            print(exc)
    return yamlD

def write_yaml(yamlD, paramsfile):
    with open(paramsfile, 'w') as params:
        yaml.dump(yamlD, stream=params, indent=2,  default_flow_style=False)


def update_nested_dict(d, other):
# Can't just update at top level, need to update nested params
#https://code.i-harness.com/en/q/3154af
    for k, v in other.items():
        if isinstance(v, collections.Mapping):
            d_v = d.get(k)
            if isinstance(d_v, collections.Mapping):
                update_nested_dict(d_v, v)
            else:
                d[k] = v.copy()
        else:
            d[k] = v

def build_dirs(workdir, params):
    # set up dirs, basename
    # defaults
    params['rules_dir'] = os.path.join(workdir, 'rules')
    params['animals_dir'] = os.path.join(workdir, "common", "animals")
    # basename
    if not params['basename']:
        params['basename'] = 'eelpond'
    basename = params['basename']
    # outdir, logsdir, assemblydir
    if params.get('experiment'):
        outdir = basename + "_out_" + params['experiment']
    else:
        outdir = basename + '_out'
    params['out_dir'] = outdir
    params['logs_dir'] =  os.path.join(outdir, 'logs')
    params['assembly_dir'] =  os.path.join(outdir, 'assembly')
    #build dir structure from default params
    for prog, prog_params in params.items():
        if isinstance(prog_params, dict):
            prog_dirname = prog_params.get('eelpond_dirname', prog)
            params[prog]['eelpond_dirname'] = os.path.join(outdir, prog_dirname)
    return params


### check link data vs ftp data ### !!!


def main(args):
    # first, find the Snakefile and configfile
    print('\n--------')
    print('checking for required files:')
    print('--------\n')
    
    thisdir = os.path.abspath(os.path.dirname(__file__))
    snakefile = find_Snakefile(thisdir)
    configfile = find_yaml(thisdir, args.configfile, 'configfile') # find configfile
    if not configfile:
        sys.stderr.write('Error: cannot find configfile {}\n'.format(args.configfile))
        sys.exit(-1)
    
    # grab all params in user config file 
    configD = read_yaml(configfile)
    # next, grab default parameters from the *_params.yaml files. 
    paramsD = build_params(thisdir) 
    update_nested_dict(paramsD,configD) # configD takes priority over default params 
    paramsD = build_dirs(thisdir, paramsD) # build dir structure
    
    if paramsD['assembly_input']['assembly']:
        assemblyfile = paramsD['assembly_input']['assembly']
        assert os.path.exists(assemblyfile), 'Error: cannot find input assembly at {}\n'.format(assemblyfile) 
        sys.stderr.write('\tFound input assembly at {}\n'.format(assemblyfile))
        gtmap = paramsD['assembly_input']['gene_trans_map']
        assert os.path.exists(gtmap), 'Error: cannot find assembly gene_trans_map at {}\n'.format(gtmap) 
        sys.stderr.write('\tFound input assembly gene-transcript map at {}\n'.format(gtmap))
        
    # Note: Passing a configfile allows nested yaml/dictionary format. 
    # Passing these params in via `config` would require a flat dictionary.
    paramsfile = os.path.join(os.path.dirname(configfile), '.ep_' + os.path.basename(configfile))
    sys.stderr.write('\tAdded default parameters from rule-specific params files.\n\tWriting full params to {}\n'.format(paramsfile))
    write_yaml(paramsD, paramsfile)

    print('--------')
    print('details!')
    print('\tsnakefile: {}'.format(snakefile))
    print('\tconfig: {}'.format(configfile))
    print('\tparams: {}'.format(paramsfile))
    print('\ttargets: {}'.format(repr(args.targets)))
    print('--------')

    # run!!
    # params file becomes snakemake config
    status = snakemake.snakemake(snakefile, configfile=paramsfile, use_conda=True, 
                                 targets=args.targets, printshellcmds=True,
                                 dryrun=args.dry_run, lock=not args.nolock,
                                 verbose=args.verbose, debug_dag=args.debug)
    
    if status: # translate "success" into shell exit code of 0
       return 0
    return 1



if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='run snakemake eelpond', usage='''run_eelpond <configfile.yaml>  [<target> ...]

Run eelpond snakemake workflows, using the given configfile.

Targets:

   full             - run full workflow (default)
   quality_trim     - preprocess reads (fastqc, trimmomatic)
   kmer_trim        - kmer trim preprocessed reads
   assemble         - transcriptome assembly 
   annotate         - annotate transcriptome assembly
   quantify         - read quantification 
   quality          - assess assembly quality (busco, transrate)
   diff_expression  - differential expression analysis
   clean            - remove target dirs 

For a quickstart, run this:

   conf/run_eelpond nema-test full

from the main eelpond directory.

''')

    parser.add_argument('configfile')
    parser.add_argument('targets', nargs='*', default=['full'])
    parser.add_argument('-n', '--dry-run', action='store_true')
    parser.add_argument('-v', '--verbose', action='store_true')
    parser.add_argument('-d', '--debug', action='store_true')
    parser.add_argument('--nolock', action='store_true')
    parser.add_argument('--unlock', action='store_true')
    parser.add_argument('--experiment', default=None)
    ### to do: enable the option below
    parser.add_argument('--build_paramsfile', action='store_true', help='just build the default parameter file')
    args = parser.parse_args()

    sys.exit(main(args))
