khmer:
  elvers_params:
    input_options:
      read:
        - trimmed
        - rcorrector_trimmed
        - raw
    output_options:
      kmer_raw:
        input: raw
        outdir: preprocess/khmer
        extensions:
          read:
            common_ext: 
              - ".khmer.fq.gz"
            pe:
              - '_1.khmer.fq.gz'
              - '_2.khmer.fq.gz'
              - '.paired.khmer.fq.gz'
              - '.single.khmer.fq.gz'
            se:
              - '.se.khmer.fq.gz'
      kmer_trimmed:
        input: trimmed
        outdir: preprocess/khmer
        extensions:
          read:
            common_ext: 
              - ".khmer.fq.gz"
            pe:
              - '_1.khmer.fq.gz'
              - '_2.khmer.fq.gz'
              - '.paired.khmer.fq.gz'
              - '.single.khmer.fq.gz'
            se:
              - '.se.khmer.fq.gz'
    help: "The khmer software is a set of command-line tools for working with DNA shotgun sequencing data from genomes, transcriptomes, metagenomes, and single cells. khmer can make de novo assemblies faster, and sometimes better. khmer can also identify (and fix) problems with shotgun data."
    citations:
      - "Crusoe MR, Alameldin HF, Awad S et al. The khmer software package: enabling efficient nucleotide sequence analysis. F1000Research 2015, 4:900 (https://doi.org/10.12688/f1000research.6924.1)"
  program_params:
    inputs:
      - trimmed
    diginorm: True
    ksize: 20
    Z: 18
    C: 3
    memory: 4e9
    coverage: 20
    extra: ""
