salmon:
  elvers_params:
    outdir: quant
    extensions: 
      read:
        combine_units: True
        pe:
          - _x___assembly__.salmon/quant.sf
          - _x___assembly__.salmon/lib_format_counts.json
        se:
          - _x___assembly__.salmon/quant.sf
          - _x___assembly__.salmon/lib_format_counts.json
      base:
          - .salmonindex
  program_params:
    input_trimmomatic_trimmed: True
    index_params:
      extra: '' # extra info for the program
    quant_params:
      libtype: A
      extra: ''
