sourmash:
  elvers_params:
    input_options:
      read:
        - kmer_trimmed
        - trimmed
        - raw
      base:
        - fasta
    output_options:
      sourmash_signature:
        input: any
        outdir: sourmash 
        extensions: 
          base:
            - .fasta.sig
          read:
            pe:
              - .fq.sig
            se:
              - .fq.sig 
  program_params:
    inputs: 
      - kmer_trimmed
      - fasta
    k_size: 21 #,31,51
    scaled: 1000
    extra: ''
