sourmash:
  elvers_params:
    input_options:
      read:
        - trimmed
        - raw
      base:
        - fasta
    output_options:
      sourmash_signature:
        input: any
        outdir: sourmash 
        extensions: 
          base:
            - .sig
          read:
            pe:
              - .paired.khmer.fq.sig
            se:
              - .se.khmer.fq.sig 
  program_params:
    inputs: 
      - kmer_trimmed
      - fasta
    k_size: 31
    scaled: 1000
    extra: ''
