bowtie2:
  elvers_params:
    input_options:
      read:
        - trimmed
        - raw
    outputs:
      name: bowtie2_mapped
      outdir: 'bowtie2'
      extensions:
        read:
          pe:
            - '.pe.bam'
          se:
            - '.se.bam'
    help: "To run the bowtie2 rule, please provide input data, and either 1) run reference generation, or 2) provide a reference via the `get_reference` utility"
    citations:
      - "Langmead B, Salzberg S. Fast gapped-read alignment with Bowtie 2. Nature Methods. 2012, 9:357-359"
  program_params:
    extra: ''
