trinity:
  elvers_params:
    input_options:
      read:
        - kmer_trimmed
        - trimmed
        - raw
    output_options:
      fasta:
        input: any
        outdir: assembly
        extensions:
          reference_extensions: # use this extension only for all output of this assembler
            - _trinity
          base:
            - .fasta
            - .fasta.gene_trans_map
  program_params:
    inputs:
      - kmer_trimmed
    # do we want to assemble the single reads with pe reads?
    add_single_to_paired: False
    max_memory: 4G
    seqtype: fq
    extra: ''

