deseq2:
  elvers_params:
    input_options:
      read:
        - salmon_quant
    output_options:
      deseq2_diffexp:
        input: salmon_quant
        outdir: diffexp
        combine_units: True # needs to match with salmon's combine_units
        extensions:
          base:
            - .deseq2.rds
            - .deseq2.pca.pdf
            - .c__contrast__.deseq2.tsv
            - .c__contrast__.deseq2.padj_0.1.tsv
            - .c__contrast__.deseq2.ma-plot.pdf
    help: "deseq2 can be used to conduct differential expression analysis of RNAseq data."
    citations: 
      - "Love, M.I., Huber, W., Anders, S. (2014) Moderated estimation of fold change and dispersion for RNA-seq data with DESeq2. Genome Biology, 15:550. 10.1186/s13059-014-0550-8"
  program_params:
    inputs: 
      - salmon_quant
    gene_trans_map: True
    # contrasts for the deseq2 results method
    contrasts:
      time0-vs-time6:
        - time0
        - time6
    pca:
      labels:
      # columns of sample sheet to use for PCA
        - condition
