fastqc:
  elvers_params:
    outdir: preprocess/fastqc
    extensions: 
      read:
        pe:
          - '_1_fastqc.zip'
          - '_1_fastqc.html'
          - '_1.trim_fastqc.zip'
          - '_1.trim_fastqc.html'
          - '_2_fastqc.zip'
          - '_2_fastqc.html'
          - '_2.trim_fastqc.zip'
          - '_2.trim_fastqc.html'
        se:
          - '_1_fastqc.zip'
          - '_1_fastqc.html'
          - '_se.trim_fastqc.zip'
          - '_se.trim_fastqc.html'
  program_params:
    extra: ''
