trimmomatic:
  elvers_params:
    input_options:
      read:
        - raw
    output_options:
      trimmed:
        input: raw
        outdir: preprocess
        extensions:
          read:
            common_ext: 
              - ".trim.fq.gz"
            pe:
              - "_1.trim.fq.gz"
              - "_2.trim.fq.gz"
              - "_1.se.trim.fq.gz"
              - "_2.se.trim.fq.gz"
            se:
              - "_se.trim.fq.gz"
  program_params:
    inputs: 
      - raw
    trim_cmd: "ILLUMINACLIP:{}:2:40:15 LEADING:2 TRAILING:2 SLIDINGWINDOW:4:5 MINLEN:25"
    adapter_file:
      pe_path: "utils/TruSeq3-PE-2.fa"
      se_path: "utils/TruSeq3-SE.fa"
      #pe_url: "https://raw.githubusercontent.com/timflutre/trimmomatic/master/adapters/TruSeq3-PE-2.fa"
      #se_url: "https://raw.githubusercontent.com/timflutre/trimmomatic/master/adapters/TruSeq3-SE.fa"
    extra: ''
